### ISSUE TITLE
Assign certificate to IWS application server

### ISSUE THREAD

**Issue by spirjade** [ThePrez/DCM-tools#34]
I tried to assign certificate to IWS application 

App name : QIBM_HTTP_SERVER_DFTIWSASRV

but getting error

The parameter [1]: Parameter value is not valid.

Is it possible to assign certificate with current code for such application server?

**Comment by ThePrez** [comment]
The `dcmassign` command is minimally tested, but I was not able to recreate this. Can you please re-run with `-v` and provide the output? Thanks!

**Comment by NickFrazee** [comment]
I am having the same problem.  I ran it with the -v and here is the output. 

-bash-5.1$ dcmassign -v
Enter application ID: QIBM_HTTP_SERVER_UPDLOTLOC
Assigning to QIBM_HTTP_SERVER_UPDLOTLOC
Enter certificate ID: **********
com.ibm.as400.access.ExtendedIllegalArgumentException: The parameter [1]: Parameter value is not valid.
        at com.ibm.as400.access.ServiceProgramCall.run(ServiceProgramCall.java:321)
        at com.github.ibmioss.dcmtools.utils.DcmApiCaller.runProgram(DcmApiCaller.java:253)
        at com.github.ibmioss.dcmtools.utils.DcmApiCaller.callQycdUpdateCertUsage(DcmApiCaller.java:161)
        at com.github.ibmioss.dcmtools.DcmAssignCmd.main(DcmAssignCmd.java:154)
